### ISSUE TITLE
API Application routing

### ISSUE THREAD

**Issue by muhakh** [joomla-projects/gsoc17_webservices#7]
Research and implement a way to write the routing for the api project.

**Comment by muhakh** [comment]
I think of the routing to be as following
Each extension would have a JSON file for the routes like this [file](https://github.com/joomla/downloads.joomla.org/blob/696d2077f0afb9354bcd082707a7e229de4e5093/libraries/api/application/open_api.json) .
The app router function will loop over that file and add each map to the router object using `addRoute` function then trigger the event ('onAfterApiRoute') which has a reference to the router object as  an argument.
The event listeners will have the ability to add more routes to the router object using `addRoute` function as follows:
```
class ApiListener
{
    function onAfterApiRoute(EventInterface $event)
    {
        $route = $event->getArgument('route');
        $route->addRoute('GET', '/article/:article_id', 'Acme\\ArticleController');
    }
}
```
@wilsonge , Is this approach what you have in mind ?

**Comment by wilsonge** [comment]
I'm not sure an extension needs a full json file. A lot of those things (aside from the routes and response definitions are CMS wide not per component e.g. swagger version, host, base path, schemes etc).

Also don't forget ideally we do not want to have custom single task controllers. We want to point them to multi-task controllers using `Joomla\Cms\Controller\ControllerInterface` which is a bit more complicated as you need a task in the definition (plus a clear way of getting that namespaced controller)

Honestly I'm unsure whether we just force extensions to write their own plugins so they can be disabled (think most extensions bundle extra plugins for things like search (e.g. https://github.com/joomla/joomla-cms/blob/staging/plugins/finder/contacts/contacts.php) anyhow or if we go down this custom file approach. Can we come up with a better idea of how this custom file works. I think it might need to be PHP controlled rather than a raw json file

**Comment by muhakh** [comment]
I found this [approach](http://www.django-rest-framework.org/api-guide/routers/) . It's for Django/Python but I find it a good concept for making RESTful routing.
**(*Note*) In django, they call controllers views and call views templates so it might be confusing.**
It applies convention over configuration and I don't know where does Joomla stand in this fight, but it worths the shot.

**Comment by wilsonge** [comment]
It's cool :) I use python nearly every day at work so not a big deal.

This approach is largely what I assumed we'd do but we don't really want to boot every single controller in the CMS up when we register the webservice. I think we will have to return a string probably rather than the controller instance, then only once we've matched the route build up the instance. 

Can you please research any alternative approaches and document the pro's and con's on a page here https://github.com/joomla-projects/gsoc17_webservices/tree/master (just create a new page in your PR)
